Update publish.yml
Signed-off-by: DARSAN <iamspdarsan@gmail.com>

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -5,60 +5,78 @@ on:
     types: [trigger-action]
   workflow_dispatch:
 
-# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
 permissions:
   contents: read
   pages: write
   id-token: write
 
-# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
-# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
 concurrency:
   group: "pages"
   cancel-in-progress: false
 
 jobs:
-  # Build job
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
       - name: Cloning
         env:
-         PAT: ${{ secrets.PAT }}
+          PAT: ${{ secrets.PAT }}
         run: |
-         git clone https://x-access-token:${PAT}@github.com/cresteem/BONSE.git
-         cd BONSE
+          git clone https://x-access-token:${PAT}@github.com/cresteem/BONSE.git
+          
+      - name: Detect package manager
+        id: detect-package-manager
+        working-directory: BONSE
+        run: |
+          if [ -f "yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_ENV
+            echo "command=install" >> $GITHUB_ENV
+            echo "runner=yarn" >> $GITHUB_ENV
+            exit 0
+          elif [ -f "package-lock.json" ]; then
+            echo "manager=npm" >> $GITHUB_ENV
+            echo "command=ci" >> $GITHUB_ENV
+            echo "runner=npx --no-install" >> $GITHUB_ENV
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: "21"
-          cache: yarn
+          cache: ${{ env.manager }}
+
       - name: Setup Pages
         uses: actions/configure-pages@v5
         with:
           static_site_generator: next
+
       - name: Restore cache
         uses: actions/cache@v4
         with:
-          path: |
-            .next/cache
-          # Generate a new cache whenever packages or source files change.
-          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
-          # If source files changed but packages didn't, rebuild from a prior cache.
-          restore-keys: |
-            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+          path: BONSE/.next/cache
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('BONSE/**/package-lock.json', 'BONSE/**/yarn.lock') }}-${{ hashFiles('BONSE/**.[jt]s', 'BONSE/**.[jt]sx') }}
+          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('BONSE/**/package-lock.json', 'BONSE/**/yarn.lock') }}-
+
       - name: Install dependencies
-        run: yarn install
+        working-directory: BONSE
+        run: ${{ env.manager }} ${{ env.command }}
+
       - name: Build with Next.js
-        run: yarn build
+        working-directory: BONSE
+        run: ${{ env.runner }} next build
+
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          path: ./bonse_out
+          path: BONSE/bonse_out  # Adjust to your actual output directory
 
-  # Deployment job
   deploy:
     environment:
       name: github-pages
